variables:
  PYTHON_APP_NAME: "th2-json-stream-provider-py"
  PYTHON_VERSION: "0.0.1"
  PYPI_PUBLISH_ENABLED: "false"
  DOCKER_PUBLISH_ENABLED: "true"
  TEST_ENABLED: "true"

include:
  - project: "vivarium/th2/pipelines"
    ref: v3
    file: "/.gitlab-ci-python.yml"

safety-check:
  image: python:3.8-slim
  tags:
    - dind
  stage: meta
  before_script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install safety
  script:
    - echo '------------ Install requirements -------------'
    - pip install -r requirements.txt
    - echo '-------------- Do safety checks ---------------'
    - safety check --short-report &> safety-check-report.txt
    - exit_code=$?
    - cat safety-check-report.txt 
    - |
      if [ $exit_code -ne 0 ]; then
        echo "safety check failure, exit code $exit_code"
        exit 1
      fi
  artifacts:
    when: always
    expire_in: "1 week"
    paths:
      - safety-check-report.txt