variables:
  PYTHON_APP_NAME: "th2-json-stream-provider-py"
  PYTHON_VERSION: "0.0.1"
  PYPI_PUBLISH_ENABLED: "false"
  DOCKER_PUBLISH_ENABLED: "true"

stages:
- meta
- build
- publish
- test

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - project: "vivarium/th2/pipelines"
    ref: v3
    file: "/.gitlab-ci-python.yml"