variables:
  PYTHON_APP_NAME: "th2-json-stream-provider-py"
  PYTHON_VERSION: "0.0.1"
  PYPI_PUBLISH_ENABLED: "false"
  DOCKER_PUBLISH_ENABLED: "true"

include:
  - project: "vivarium/th2/pipelines"
    ref: v3
    file: "/.gitlab-ci-python.yml"

audit-check:
  image: python:3.8-slim
  tags:
    - dind
  stage: meta
  before_script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install pip-audit
  script:
    - echo '------------ Install requirements -------------'
    - pip install -r requirements.txt
    - echo '-------------- Do safety checks ---------------'
    - pip-audit

safety-check:
  image: python:3.8-slim
  tags:
    - dind
  stage: meta

  before_script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install safety
  script:
    - echo '------------ Install requirements -------------'
    - pip install -r requirements.txt
    - echo '-------------- Do safety checks ---------------'
    - safety check --short-report --key e46147a4-e285-41c9-95b6-9832338ad98d