services:
  json_stream_provider:
    image: ghcr.io/th2-net/th2-json-stream-provider-py:0.0.3-compose-9418538929-b1c820e
    ports:
      - "8081:8080"
    volumes:
      - j_sp_volume:/home/json-stream/:rw
      - jupyter_volume:/home/jovyan/:rw
      - ${USER_DATA_DIR}:/home/jovyan/user-data/:ro
      - ./json-stream-provider/custom.json:/var/th2/config/custom.json:ro
    networks:
      - th2_network

  jupyter_notebook:
    build:
      context: ./jupyter-notebook
      dockerfile: Dockerfile
    ports:
      - "8082:8888"
    volumes:
      - jupyter_volume:/home/jovyan/:rw
      - ${USER_DATA_DIR}:/home/jovyan/user-data/:rw
    networks:
      - th2_network

  th2_rpt_viewer:
    image: ghcr.io/th2-net/th2-rpt-viewer:5.2.7-th2-5142-9416197441
    ports:
      - "8083:8080"
    networks:
      - th2_network

  nginx_reverse_proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - th2_network

volumes:
  jupyter_volume:
  j_sp_volume:

networks:
  th2_network: