name: Build and publish dev release Docker image to Github Container Registry ghcr.io

on: workflow_dispatch

jobs:
  get-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Get package version
        id: pack_ver
        uses: notiz-dev/github-action-json-property@release
        with:
          path: package_info.json
          prop_path: package_version
      - name: Show version
        run: echo ${{ steps.pack_ver.outputs.prop }}
    outputs:
      versionNumber: ${{ steps.pack_ver.outputs.prop }}
      version: ${{ steps.pack_ver.outputs.prop }}-dev

  scan:
    name: Vulnerabilities scan
    uses: th2-net/.github/.github/workflows/python-scan.yml@main

  docker-push:
    runs-on: ubuntu-20.04
    name: Build Docker image and push to ghcr.io
    needs: [ get-version, scan ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: '.'
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ needs.get-version.outputs.version }}
          labels: com.exactpro.th2.${{ github.repository }}=${{ needs.get-version.outputs.versionNumber }}
          provenance: false
          build-args: |
            release_version=${{ needs.get-version.outputs.versionNumber }}