name: Build release

on: workflow_dispatch

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get package version
        id: pack_ver
        uses: notiz-dev/github-action-json-property@release
        with:
          path: package_info.json
          prop_path: package_version
      - name: Show version
        run: echo ${{ steps.pack_ver.outputs.prop }}
    outputs:
      version: ${{ steps.pack_ver.outputs.prop }}

  scan:
    name: Vulnerabilities scan
    uses: th2-net/.github/.github/workflows/python-scan.yml@main

  license:
    name: License scan
    needs: [ get-version ]
    uses: th2-net/.github/.github/workflows/python-license-check.yml@main
    with:
      version: ${{ needs.get-version.outputs.version }}
      python-version: 3.9

  docker-push:
    runs-on: ubuntu-latest
    name: Build Docker image and push to ghcr.io
    needs: [ get-version, scan, license ]
    steps:
      - name: Show release version
        run: echo ${{ needs.get-version.outputs.version }}
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: '.'
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ needs.get-version.outputs.version }}
          labels: com.exactpro.th2.${{ github.repository }}=${{ needs.get-version.outputs.version }}
          provenance: false
          build-args: |
            release_version=${{ needs.get-version.outputs.versionNumber }}