name: Scan licenses and vulnerabilities in java project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  get-git-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get branch name
        id: branch
        run: echo "branch_name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Show git branch
        run: echo ${{ steps.branch.outputs.branch_name }}
    outputs:
      branch: ${{ steps.branch.outputs.branch_name }}
  get-commit-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get SHA of the commit
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Show short git hash
        run: echo ${{ steps.sha.outputs.sha_short }}
    outputs:
      hash: ${{ steps.sha.outputs.sha_short }}
  get-version:
    runs-on: ubuntu-latest
    needs: [ get-git-branch, get-commit-hash ]
    steps:
      - uses: actions/checkout@v5
      - name: Get package version
        id: pack_ver
        uses: notiz-dev/github-action-json-property@release
        with:
          path: package_info.json
          prop_path: package_version
      - name: Show version
        run: echo ${{ steps.pack_ver.outputs.prop }}
  scan:
    name: Vulnerabilities scan
    uses: th2-net/.github/.github/workflows/python-scan.yml@main
  license:
    name: License scan
    needs: [ get-version ]
    uses: th2-net/.github/.github/workflows/python-license-check.yml@main
    with:
      version: ${{ needs.get-version.outputs.version }}
      python-version: 3.9